### ISSUE TITLE
Mama Turtle strat: Diagonal bomb boost

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#307] opened 2019-09-27 23:59 UTC
See third strat shown at https://www.youtube.com/watch?v=kIN4ga8MMxU

**Comment by kjbranch** [comment] 2023-02-11 18:55
The originally shared video link is broken, does anyone have a clip for it or know what the strat was?

**Comment by osse101** [comment] 2023-02-13 02:41
I think #431 is a duplicate of this.  And this has now been resolved.

**Closed** 2023-02-13 02:50 UTC
Labels: Strat:High-Level
